name: Test & Deploy @ fly.io
on:
  push:
    branches: [main, deploy_from_github]

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.3
          with:
            args: "deploy"
