name: Test & Deploy @ fly.io

on: push

env:
  elixir-version: '1.13.3'
  erlang-version: '24.2.1'
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-elixir:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.erlang-version }}-${{ env.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          export MIX_ENV=test
          mix deps.get
          mix deps.compile
          
  test-elixir:
    needs:
      - build-elixir
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.erlang-version }}-${{ env.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix ci

  deploy:
    needs:
      - test-elixir
    name: Deploy app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy"
